### ISSUE TITLE
flask-server startet mit "not found"

### ISSUE THREAD

**Issue by hansimglueck** [hansimglueck/teledisko#10]
check it out

**Comment by 8JupiterMoll8** [comment]
Die app.py war auf` port **5051**  `
Description=Chromium Kiosk
Wants=graphical.target
After=graphical.target
#teleflask-server.service

[Service]
Environment=DISPLAY=:0
Environment=XAUTHORITY=/home/alphi/.Xauthority
#Type=simple
ExecStart=/usr/bin/chromium-browser --hide-cursor --kiosk http://localhost:**5000**
#ExecStart=/bin/bash /home/alphi/kiosk.sh 

Habe die app.py auf port 5000 eingesellt

**Comment by 8JupiterMoll8** [comment]
Solve
